from sqlalchemy import Column, Integer, String
from app.database import Base

# Database model representing a job application
class Job(Base):
    __tablename__ = "jobs"

    # Primary key automatically generated by the database
    id = Column(Integer, primary_key=True, index=True)

    # Company name
    company = Column(String, nullable=False)

    # Job title
    title = Column(String, nullable=False)

    # Current application status
    status = Column(String, nullable=False)